# Generated by Django 4.2.6 on 2023-10-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='questionsSolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='timeElapsed',
            field=models.IntegerField(default=0),
        ),
    ]
