# Generated by Django 4.2.6 on 2023-10-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_login_questionssolved_login_timeelapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
    ]
